# Generated by Django 3.1.1 on 2020-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
