# Generated by Django 3.1.1 on 2020-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=20, verbose_name='Title')),
                ('pub_date', models.DateField(verbose_name='Publish Date')),
                ('content', models.CharField(max_length=20000, verbose_name='Body')),
                ('head_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
